// frontend/src/app/auth/components/login/login.component.ts
//import { HttpClient } from '@angular/common/http';
//import { HttpClientModule } from '@angular/common/http';
import { CommonModule } from '@angular/common';
import {Component, OnInit} from '@angular/core';
import {FormBuilder, FormGroup, ReactiveFormsModule, Validators} from '@angular/forms';
import {Router, RouterModule} from '@angular/router';
import {AuthService} from 'src/auth/service/auth.service';

@Component({
  selector: 'app-login',
  imports: [RouterModule,ReactiveFormsModule,CommonModule],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css',
  standalone: true,
})
export class LoginComponent implements OnInit {
  loginForm!: FormGroup;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {}

  ngOnInit(): void {
    // Create a form group with username and password controls
    this.loginForm = this.fb.group({
      username: ['', Validators.required], // 'required' validator
      password: ['', Validators.required], // 'required' validator
    });
  }

  // Submit form handler
  onSubmit(): void {
    if (this.loginForm.invalid) {
      return; // Stop if the form is invalid
    }

    

    // Call the AuthService to send data to the backend API
    this.authService.login(this.loginForm.value).subscribe(
      (response) => {
        // Handle success, e.g., store token, navigate, etc.
        console.log('Login successful:', response);
        sessionStorage.setItem('token', response.token);

        // Get user role from backend using token
        this.authService.getUserRole(this.loginForm.value.username,response.token).subscribe(
          (roleResponse) => {
            const userRole = roleResponse;

            console.log(userRole);
            // Route based on user role
            switch(userRole) {
              case 'patient':
                this.router.navigate(['/patient/dashboard']);
                break;
              case 'doctor': 
                this.router.navigate(['/doctor/dashboard']);
                break;
              case 'admin':
                this.router.navigate(['/admin/dashboard']); 
                break;
              case 'pharmacy':
                this.router.navigate(['/pharmacy/dashboard']);
                break;
              default:
                this.loginForm.setErrors({ invalidRole: true });
                console.error('Unknown user role');
            }
          },
          (error) => {
            console.error('Error getting user role:', error);
            this.loginForm.setErrors({ invalidRole: true });
          }
        );
      },
      (error) => {
        if (error.status === 404) {
          console.error('User not found');
        } else if (error.status === 401) {
          console.error('Username or password incorrect');
          this.loginForm.patchValue({
            username: '',
            password: ''
          });
          this.loginForm.setErrors({ invalidCredentials: true });
          console.log(this.loginForm.errors);
        } else if (error.status === 500) {
          console.error('Login failed');
          this.loginForm.setErrors({ invalidCredentials: true });
        }
      }
    );
  }
}
<div class="my-bg">
  <form action="" class="form-container" [formGroup]="loginForm" (ngSubmit)="onSubmit()">
    <!-- @if(isSubmitting && loginForm.errors?.['invalidCredentials']){
      <div class="alert alert-danger">Incorrect username and password</div>
    }
    @if(isSubmitting && loginForm.errors?.['invalidRole']){
      <div class="alert alert-danger">Invalid Role. Contact administrator</div>
    } -->
    <div *ngIf="loginForm.errors?.['invalidCredentials']" class="alert alert-danger mb-3">
      Incorrect username and password
    </div>
    <div *ngIf="loginForm.errors?.['invalidRole']" class="alert alert-danger mb-3">
      Invalid Role. Contact administrator
    </div>
    <div class="mb-3">
      <label for="username" class="form-label">Username</label>
      <input
        type="text"
        class="form-control"
        id="username"
        formControlName="username"
        placeholder="Enter your username"
      />
    </div>
    <div class="mb-3">
      <label for="password" class="form-label">Password</label>
      <input
        type="password"
        name="password"
        id="password"
        class="form-control"
        formControlName="password"
        placeholder="Enter your password"
      />
    </div>
    <button type="submit" class="btn btn-primary btn-center">Submit</button>
    <p>
      New User? <a routerLink="/register" class="text-primary">Register Here</a>
    </p>
  </form>
</div>

// frontend/src/auth/Login.tsx
import React, { useState } from 'react';
import {
  TextField,
  Button,
  Typography,
  Container,
  Box,
} from '@mui/material';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';

const Login: React.FC = () => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const navigate = useNavigate();

  const handleLogin = async (event: React.FormEvent) => {
    event.preventDefault();
    setError(''); // Clear any previous error

    try {
      // Send login request to backend
      // Send login request to backend using GET
const response = await axios.post(`http://localhost:5000/api/users/login`, {
    username,
    password
});


if (response.status === 200 && response.data.token) {
  // Extract the JWT token from the response
  const token = response.data.token;

  // Fetch user role after successful login, using the token in the Authorization header
  const roleResponse = await axios.get(`http://localhost:5000/api/users/${username}/role`, {
    headers: {
      Authorization: `Bearer ${token}`
    }
  });

  // Get the user role from the response
  const userRole = roleResponse.data;
  console.log(userRole);
  sessionStorage.setItem('token', token);

        // Route based on role
        if (userRole === 'patient') {
          navigate('/patient/dashboard');
        } else if (userRole === 'doctor') {
          navigate('/doctor/dashboard');
        } else if (userRole === 'admin') {
          navigate('/admin/dashboard');
        } else {
          setError('Unrecognized role.');
        }
      } else {
        setError('Invalid username or password.');
      }
    } catch (error) {
      console.error('Login error', error);
      setError('Login failed. Please check your credentials and try again.');
    }
  };

  return (
    <Container component="main" maxWidth="xs">
      <Box sx={{ mt: 8, mb: 2 }}>
        <Typography component="h1" variant="h5">
          Login
        </Typography>
        {error && <Typography color="error">{error}</Typography>}
        <form onSubmit={handleLogin}>
          <TextField
            margin="normal"
            required
            fullWidth
            label="Username"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
          />
          <TextField
            margin="normal"
            required
            fullWidth
            label="Password"
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
          <Button
            type="submit"
            fullWidth
            variant="contained"
            color="primary"
            sx={{ mt: 3, mb: 2 }}
          >
            Login
          </Button>
        </form>
      </Box>
    </Container>
  );
};

export default Login;
